
export const INPUT_BASE_CURRENCY = 'INPUT_BASE_CURRENCY'
export const INPUT_TARGET_CURRENCY = 'INPUT_TARGET_CURRENCY'

export const SELECT_BASE_CURRENCY = 'SELECT_BASE_CURRENCY'
export const SELECT_TARGET_CURRENCY = 'SELECT_TARGET_CURRENCY'

export const SET_CONVERSION_RATES = 'SET_CONVERSION_RATES'

export const GET_CONVERSION_DATA = 'GET_CONVERSION_DATA'
export const SET_DATE_CURRENCY_RATE = 'SET_DATE_CURRENCY_RATE'
export const GET_DATE_CURRENCY_RATE = 'GET_DATE_CURRENCY_RATE'
export const SET_BASE = 'SET_BASE'
export const SET_THEME = 'SET_THEME'
export const FETCH_ERROR = 'FETCH_ERROR'

export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
